//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.18 at 04:52:34 PM PDT 
//


package com.oracle.beehive;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for categoryApplicationUpdateParameter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="categoryApplicationUpdateParameter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="categoryApplicationUpdater" type="{http://www.oracle.com/beehive}categoryApplicationUpdater" minOccurs="0"/>
 *         &lt;element name="categoryTemplateHandle" type="{http://www.oracle.com/beehive}beeId" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "categoryApplicationUpdateParameter", propOrder = {
    "categoryApplicationUpdater",
    "categoryTemplateHandle"
})
public class CategoryApplicationUpdateParameter {

    protected CategoryApplicationUpdater categoryApplicationUpdater;
    protected BeeId categoryTemplateHandle;

    /**
     * Gets the value of the categoryApplicationUpdater property.
     * 
     * @return
     *     possible object is
     *     {@link CategoryApplicationUpdater }
     *     
     */
    public CategoryApplicationUpdater getCategoryApplicationUpdater() {
        return categoryApplicationUpdater;
    }

    /**
     * Sets the value of the categoryApplicationUpdater property.
     * 
     * @param value
     *     allowed object is
     *     {@link CategoryApplicationUpdater }
     *     
     */
    public void setCategoryApplicationUpdater(CategoryApplicationUpdater value) {
        this.categoryApplicationUpdater = value;
    }

    /**
     * Gets the value of the categoryTemplateHandle property.
     * 
     * @return
     *     possible object is
     *     {@link BeeId }
     *     
     */
    public BeeId getCategoryTemplateHandle() {
        return categoryTemplateHandle;
    }

    /**
     * Sets the value of the categoryTemplateHandle property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeeId }
     *     
     */
    public void setCategoryTemplateHandle(BeeId value) {
        this.categoryTemplateHandle = value;
    }

}
