//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.18 at 04:52:34 PM PDT 
//


package com.oracle.beehive;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for emailDraftUpdater complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="emailDraftUpdater">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.oracle.com/beehive}messageUpdater">
 *       &lt;sequence>
 *         &lt;element name="contentUpdater" type="{http://www.oracle.com/beehive}emailMessageContentUpdater" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.oracle.com/beehive}emailMessageType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "emailDraftUpdater", propOrder = {
    "contentUpdater",
    "type"
})
@XmlRootElement(name = "emailDraftUpdater")
public class EmailDraftUpdater
    extends MessageUpdater
{

    protected EmailMessageContentUpdater contentUpdater;
    protected EmailMessageType type;

    /**
     * Gets the value of the contentUpdater property.
     * 
     * @return
     *     possible object is
     *     {@link EmailMessageContentUpdater }
     *     
     */
    public EmailMessageContentUpdater getContentUpdater() {
        return contentUpdater;
    }

    /**
     * Sets the value of the contentUpdater property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmailMessageContentUpdater }
     *     
     */
    public void setContentUpdater(EmailMessageContentUpdater value) {
        this.contentUpdater = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link EmailMessageType }
     *     
     */
    public EmailMessageType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmailMessageType }
     *     
     */
    public void setType(EmailMessageType value) {
        this.type = value;
    }

}
