//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.18 at 04:52:34 PM PDT 
//


package com.oracle.beehive;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for emailMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="emailMessage">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.oracle.com/beehive}message">
 *       &lt;sequence>
 *         &lt;element name="BCCReceivers" type="{http://www.oracle.com/beehive}participant" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CCReceivers" type="{http://www.oracle.com/beehive}participant" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="content" type="{http://www.oracle.com/beehive}emailMessageContent" minOccurs="0"/>
 *         &lt;element name="contentSnapshotId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deliveryInfo" type="{http://www.oracle.com/beehive}emailDeliveryInfo" minOccurs="0"/>
 *         &lt;element name="flags" type="{http://www.oracle.com/beehive}messageFlag" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="from" type="{http://www.oracle.com/beehive}participant" minOccurs="0"/>
 *         &lt;element name="messageIdentifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="repairAttemptCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="replyTo" type="{http://www.oracle.com/beehive}participant" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="scanResults" type="{http://www.oracle.com/beehive}virusScanResult" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="toReceivers" type="{http://www.oracle.com/beehive}participant" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.oracle.com/beehive}emailMessageType" minOccurs="0"/>
 *         &lt;element name="UID" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="virusDefinitionId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="virusScanDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="virusScanStatus" type="{http://www.oracle.com/beehive}virusScanStatus" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "emailMessage", propOrder = {
    "bccReceivers",
    "ccReceivers",
    "content",
    "contentSnapshotId",
    "deliveryInfo",
    "flags",
    "from",
    "messageIdentifier",
    "repairAttemptCount",
    "replyTos",
    "scanResults",
    "size",
    "toReceivers",
    "type",
    "uid",
    "virusDefinitionId",
    "virusScanDate",
    "virusScanStatus"
})
@XmlRootElement(name = "emailMessage")
public class EmailMessage
    extends Message
{

    @XmlElement(name = "BCCReceivers")
    protected List<Participant> bccReceivers;
    @XmlElement(name = "CCReceivers")
    protected List<Participant> ccReceivers;
    protected EmailMessageContent content;
    protected String contentSnapshotId;
    protected EmailDeliveryInfo deliveryInfo;
    @XmlElement(nillable = true)
    protected List<MessageFlag> flags;
    protected Participant from;
    protected int messageIdentifier;
    protected int repairAttemptCount;
    @XmlElement(name = "replyTo")
    protected List<Participant> replyTos;
    @XmlElement(nillable = true)
    protected List<VirusScanResult> scanResults;
    protected long size;
    protected List<Participant> toReceivers;
    protected EmailMessageType type;
    @XmlElement(name = "UID")
    protected long uid;
    protected Integer virusDefinitionId;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar virusScanDate;
    protected VirusScanStatus virusScanStatus;

    /**
     * Gets the value of the bccReceivers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bccReceivers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBCCReceivers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Participant }
     * 
     * 
     */
    public List<Participant> getBCCReceivers() {
        if (bccReceivers == null) {
            bccReceivers = new ArrayList<Participant>();
        }
        return this.bccReceivers;
    }

    /**
     * Gets the value of the ccReceivers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ccReceivers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCCReceivers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Participant }
     * 
     * 
     */
    public List<Participant> getCCReceivers() {
        if (ccReceivers == null) {
            ccReceivers = new ArrayList<Participant>();
        }
        return this.ccReceivers;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link EmailMessageContent }
     *     
     */
    public EmailMessageContent getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmailMessageContent }
     *     
     */
    public void setContent(EmailMessageContent value) {
        this.content = value;
    }

    /**
     * Gets the value of the contentSnapshotId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentSnapshotId() {
        return contentSnapshotId;
    }

    /**
     * Sets the value of the contentSnapshotId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentSnapshotId(String value) {
        this.contentSnapshotId = value;
    }

    /**
     * Gets the value of the deliveryInfo property.
     * 
     * @return
     *     possible object is
     *     {@link EmailDeliveryInfo }
     *     
     */
    public EmailDeliveryInfo getDeliveryInfo() {
        return deliveryInfo;
    }

    /**
     * Sets the value of the deliveryInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmailDeliveryInfo }
     *     
     */
    public void setDeliveryInfo(EmailDeliveryInfo value) {
        this.deliveryInfo = value;
    }

    /**
     * Gets the value of the flags property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the flags property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlags().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MessageFlag }
     * 
     * 
     */
    public List<MessageFlag> getFlags() {
        if (flags == null) {
            flags = new ArrayList<MessageFlag>();
        }
        return this.flags;
    }

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link Participant }
     *     
     */
    public Participant getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link Participant }
     *     
     */
    public void setFrom(Participant value) {
        this.from = value;
    }

    /**
     * Gets the value of the messageIdentifier property.
     * 
     */
    public int getMessageIdentifier() {
        return messageIdentifier;
    }

    /**
     * Sets the value of the messageIdentifier property.
     * 
     */
    public void setMessageIdentifier(int value) {
        this.messageIdentifier = value;
    }

    /**
     * Gets the value of the repairAttemptCount property.
     * 
     */
    public int getRepairAttemptCount() {
        return repairAttemptCount;
    }

    /**
     * Sets the value of the repairAttemptCount property.
     * 
     */
    public void setRepairAttemptCount(int value) {
        this.repairAttemptCount = value;
    }

    /**
     * Gets the value of the replyTos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the replyTos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReplyTos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Participant }
     * 
     * 
     */
    public List<Participant> getReplyTos() {
        if (replyTos == null) {
            replyTos = new ArrayList<Participant>();
        }
        return this.replyTos;
    }

    /**
     * Gets the value of the scanResults property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scanResults property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScanResults().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VirusScanResult }
     * 
     * 
     */
    public List<VirusScanResult> getScanResults() {
        if (scanResults == null) {
            scanResults = new ArrayList<VirusScanResult>();
        }
        return this.scanResults;
    }

    /**
     * Gets the value of the size property.
     * 
     */
    public long getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     */
    public void setSize(long value) {
        this.size = value;
    }

    /**
     * Gets the value of the toReceivers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the toReceivers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getToReceivers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Participant }
     * 
     * 
     */
    public List<Participant> getToReceivers() {
        if (toReceivers == null) {
            toReceivers = new ArrayList<Participant>();
        }
        return this.toReceivers;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link EmailMessageType }
     *     
     */
    public EmailMessageType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmailMessageType }
     *     
     */
    public void setType(EmailMessageType value) {
        this.type = value;
    }

    /**
     * Gets the value of the uid property.
     * 
     */
    public long getUID() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     */
    public void setUID(long value) {
        this.uid = value;
    }

    /**
     * Gets the value of the virusDefinitionId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVirusDefinitionId() {
        return virusDefinitionId;
    }

    /**
     * Sets the value of the virusDefinitionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVirusDefinitionId(Integer value) {
        this.virusDefinitionId = value;
    }

    /**
     * Gets the value of the virusScanDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getVirusScanDate() {
        return virusScanDate;
    }

    /**
     * Sets the value of the virusScanDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setVirusScanDate(XMLGregorianCalendar value) {
        this.virusScanDate = value;
    }

    /**
     * Gets the value of the virusScanStatus property.
     * 
     * @return
     *     possible object is
     *     {@link VirusScanStatus }
     *     
     */
    public VirusScanStatus getVirusScanStatus() {
        return virusScanStatus;
    }

    /**
     * Sets the value of the virusScanStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link VirusScanStatus }
     *     
     */
    public void setVirusScanStatus(VirusScanStatus value) {
        this.virusScanStatus = value;
    }

}
