//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.18 at 04:52:34 PM PDT 
//


package com.oracle.beehive;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for expertiseTopicClause complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="expertiseTopicClause">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="relativeWeight" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="reviewed" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="termVisibility" type="{http://www.oracle.com/beehive}visibility" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "expertiseTopicClause", propOrder = {
    "relativeWeight",
    "reviewed",
    "termVisibilities"
})
@XmlSeeAlso({
    ExpertiseTopNClause.class,
    ExpertiseTopicSearchClause.class
})
public class ExpertiseTopicClause {

    protected int relativeWeight;
    protected Boolean reviewed;
    @XmlElement(name = "termVisibility", nillable = true)
    protected List<Visibility> termVisibilities;

    /**
     * Gets the value of the relativeWeight property.
     * 
     */
    public int getRelativeWeight() {
        return relativeWeight;
    }

    /**
     * Sets the value of the relativeWeight property.
     * 
     */
    public void setRelativeWeight(int value) {
        this.relativeWeight = value;
    }

    /**
     * Gets the value of the reviewed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReviewed() {
        return reviewed;
    }

    /**
     * Sets the value of the reviewed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReviewed(Boolean value) {
        this.reviewed = value;
    }

    /**
     * Gets the value of the termVisibilities property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the termVisibilities property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTermVisibilities().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Visibility }
     * 
     * 
     */
    public List<Visibility> getTermVisibilities() {
        if (termVisibilities == null) {
            termVisibilities = new ArrayList<Visibility>();
        }
        return this.termVisibilities;
    }

}
