//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.18 at 04:52:34 PM PDT 
//


package com.oracle.beehive;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for expertiseTopNClause complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="expertiseTopNClause">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.oracle.com/beehive}expertiseTopicClause">
 *       &lt;sequence>
 *         &lt;element name="count" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ignoreReviewedWords" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="minKeywordConf" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="offset" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "expertiseTopNClause", propOrder = {
    "count",
    "ignoreReviewedWords",
    "minKeywordConf",
    "offset"
})
public class ExpertiseTopNClause
    extends ExpertiseTopicClause
{

    protected int count;
    protected boolean ignoreReviewedWords;
    protected float minKeywordConf;
    protected int offset;

    /**
     * Gets the value of the count property.
     * 
     */
    public int getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     */
    public void setCount(int value) {
        this.count = value;
    }

    /**
     * Gets the value of the ignoreReviewedWords property.
     * 
     */
    public boolean isIgnoreReviewedWords() {
        return ignoreReviewedWords;
    }

    /**
     * Sets the value of the ignoreReviewedWords property.
     * 
     */
    public void setIgnoreReviewedWords(boolean value) {
        this.ignoreReviewedWords = value;
    }

    /**
     * Gets the value of the minKeywordConf property.
     * 
     */
    public float getMinKeywordConf() {
        return minKeywordConf;
    }

    /**
     * Sets the value of the minKeywordConf property.
     * 
     */
    public void setMinKeywordConf(float value) {
        this.minKeywordConf = value;
    }

    /**
     * Gets the value of the offset property.
     * 
     */
    public int getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     */
    public void setOffset(int value) {
        this.offset = value;
    }

}
