//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.18 at 04:52:34 PM PDT 
//


package com.oracle.beehive;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for expertiseTextProcessingSpec complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="expertiseTextProcessingSpec">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="boolexprMaxWords" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="desiredSearchType" type="{http://www.oracle.com/beehive}expertiseTextProcessingSearchType" minOccurs="0"/>
 *         &lt;element name="extractMaxTerms" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="maxSearchWords" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="textMaxChars" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "expertiseTextProcessingSpec", propOrder = {
    "boolexprMaxWords",
    "desiredSearchType",
    "extractMaxTerms",
    "maxSearchWords",
    "textMaxChars"
})
public class ExpertiseTextProcessingSpec {

    protected int boolexprMaxWords;
    protected ExpertiseTextProcessingSearchType desiredSearchType;
    protected int extractMaxTerms;
    protected int maxSearchWords;
    protected int textMaxChars;

    /**
     * Gets the value of the boolexprMaxWords property.
     * 
     */
    public int getBoolexprMaxWords() {
        return boolexprMaxWords;
    }

    /**
     * Sets the value of the boolexprMaxWords property.
     * 
     */
    public void setBoolexprMaxWords(int value) {
        this.boolexprMaxWords = value;
    }

    /**
     * Gets the value of the desiredSearchType property.
     * 
     * @return
     *     possible object is
     *     {@link ExpertiseTextProcessingSearchType }
     *     
     */
    public ExpertiseTextProcessingSearchType getDesiredSearchType() {
        return desiredSearchType;
    }

    /**
     * Sets the value of the desiredSearchType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpertiseTextProcessingSearchType }
     *     
     */
    public void setDesiredSearchType(ExpertiseTextProcessingSearchType value) {
        this.desiredSearchType = value;
    }

    /**
     * Gets the value of the extractMaxTerms property.
     * 
     */
    public int getExtractMaxTerms() {
        return extractMaxTerms;
    }

    /**
     * Sets the value of the extractMaxTerms property.
     * 
     */
    public void setExtractMaxTerms(int value) {
        this.extractMaxTerms = value;
    }

    /**
     * Gets the value of the maxSearchWords property.
     * 
     */
    public int getMaxSearchWords() {
        return maxSearchWords;
    }

    /**
     * Sets the value of the maxSearchWords property.
     * 
     */
    public void setMaxSearchWords(int value) {
        this.maxSearchWords = value;
    }

    /**
     * Gets the value of the textMaxChars property.
     * 
     */
    public int getTextMaxChars() {
        return textMaxChars;
    }

    /**
     * Sets the value of the textMaxChars property.
     * 
     */
    public void setTextMaxChars(int value) {
        this.textMaxChars = value;
    }

}
