//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.18 at 04:52:34 PM PDT 
//


package com.oracle.beehive;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hrefContext complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hrefContext">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hrefPrefix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="linkedEntityType" type="{http://www.oracle.com/beehive}wikiLinkedEntityType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hrefContext", propOrder = {
    "hrefPrefix",
    "linkedEntityType"
})
@XmlSeeAlso({
    HrefPathContext.class,
    HrefEidContext.class
})
public abstract class HrefContext {

    protected String hrefPrefix;
    protected WikiLinkedEntityType linkedEntityType;

    /**
     * Gets the value of the hrefPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHrefPrefix() {
        return hrefPrefix;
    }

    /**
     * Sets the value of the hrefPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHrefPrefix(String value) {
        this.hrefPrefix = value;
    }

    /**
     * Gets the value of the linkedEntityType property.
     * 
     * @return
     *     possible object is
     *     {@link WikiLinkedEntityType }
     *     
     */
    public WikiLinkedEntityType getLinkedEntityType() {
        return linkedEntityType;
    }

    /**
     * Sets the value of the linkedEntityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link WikiLinkedEntityType }
     *     
     */
    public void setLinkedEntityType(WikiLinkedEntityType value) {
        this.linkedEntityType = value;
    }

}
