//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.18 at 04:52:34 PM PDT 
//


package com.oracle.beehive;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for messageFlag.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="messageFlag">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ANSWERED"/>
 *     &lt;enumeration value="FORWARDED"/>
 *     &lt;enumeration value="REDIRECTED"/>
 *     &lt;enumeration value="HIDDEN"/>
 *     &lt;enumeration value="MARKED_DELETE"/>
 *     &lt;enumeration value="MARKED_FOR_FOLLOWUP"/>
 *     &lt;enumeration value="MDN_PROCESSED"/>
 *     &lt;enumeration value="MARKED_DRAFT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "messageFlag")
@XmlEnum
public enum MessageFlag {

    ANSWERED,
    FORWARDED,
    REDIRECTED,
    HIDDEN,
    MARKED_DELETE,
    MARKED_FOR_FOLLOWUP,
    MDN_PROCESSED,
    MARKED_DRAFT;

    public String value() {
        return name();
    }

    public static MessageFlag fromValue(String v) {
        return valueOf(v);
    }

}
