//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.18 at 04:52:34 PM PDT 
//


package com.oracle.beehive;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for occurrenceWorkspaceParticipantUpdater complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="occurrenceWorkspaceParticipantUpdater">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.oracle.com/beehive}occurrenceCompositeParticipantUpdater">
 *       &lt;sequence>
 *         &lt;element name="inviteEnrollee" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="inviteEnrollees" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "occurrenceWorkspaceParticipantUpdater", propOrder = {
    "inviteEnrollee",
    "inviteEnrollees"
})
public class OccurrenceWorkspaceParticipantUpdater
    extends OccurrenceCompositeParticipantUpdater
{

    protected boolean inviteEnrollee;
    protected boolean inviteEnrollees;

    /**
     * Gets the value of the inviteEnrollee property.
     * 
     */
    public boolean isInviteEnrollee() {
        return inviteEnrollee;
    }

    /**
     * Sets the value of the inviteEnrollee property.
     * 
     */
    public void setInviteEnrollee(boolean value) {
        this.inviteEnrollee = value;
    }

    /**
     * Gets the value of the inviteEnrollees property.
     * 
     */
    public boolean isInviteEnrollees() {
        return inviteEnrollees;
    }

    /**
     * Sets the value of the inviteEnrollees property.
     * 
     */
    public void setInviteEnrollees(boolean value) {
        this.inviteEnrollees = value;
    }

}
