//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.18 at 04:52:34 PM PDT 
//


package com.oracle.beehive;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for occurrenceParticipantUpdater complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="occurrenceParticipantUpdater">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.oracle.com/beehive}baseParticipantUpdater">
 *       &lt;sequence>
 *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deliveryChannels" type="{http://www.oracle.com/beehive}participantDeliveryChannel" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="directlyInvited" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="invitationEid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="participant" type="{http://www.oracle.com/beehive}beeId" minOccurs="0"/>
 *         &lt;element name="participantStatus" type="{http://www.oracle.com/beehive}occurrenceParticipantStatus" minOccurs="0"/>
 *         &lt;element name="propertiesUpdater" type="{http://www.oracle.com/beehive}collabPropertiesUpdater" minOccurs="0"/>
 *         &lt;element name="role" type="{http://www.oracle.com/beehive}participantRole" minOccurs="0"/>
 *         &lt;element name="rsvp" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="status" type="{http://www.oracle.com/beehive}occurrenceParticipantStatus" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "occurrenceParticipantUpdater", propOrder = {
    "address",
    "deliveryChannels",
    "directlyInvited",
    "invitationEid",
    "name",
    "participant",
    "participantStatus",
    "propertiesUpdater",
    "role",
    "rsvp",
    "status"
})
public class OccurrenceParticipantUpdater
    extends BaseParticipantUpdater
{

    protected String address;
    @XmlElement(nillable = true)
    protected List<ParticipantDeliveryChannel> deliveryChannels;
    protected Boolean directlyInvited;
    protected String invitationEid;
    protected String name;
    protected BeeId participant;
    protected OccurrenceParticipantStatus participantStatus;
    protected CollabPropertiesUpdater propertiesUpdater;
    protected ParticipantRole role;
    protected boolean rsvp;
    protected OccurrenceParticipantStatus status;

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the deliveryChannels property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deliveryChannels property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeliveryChannels().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParticipantDeliveryChannel }
     * 
     * 
     */
    public List<ParticipantDeliveryChannel> getDeliveryChannels() {
        if (deliveryChannels == null) {
            deliveryChannels = new ArrayList<ParticipantDeliveryChannel>();
        }
        return this.deliveryChannels;
    }

    /**
     * Gets the value of the directlyInvited property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDirectlyInvited() {
        return directlyInvited;
    }

    /**
     * Sets the value of the directlyInvited property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDirectlyInvited(Boolean value) {
        this.directlyInvited = value;
    }

    /**
     * Gets the value of the invitationEid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvitationEid() {
        return invitationEid;
    }

    /**
     * Sets the value of the invitationEid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvitationEid(String value) {
        this.invitationEid = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the participant property.
     * 
     * @return
     *     possible object is
     *     {@link BeeId }
     *     
     */
    public BeeId getParticipant() {
        return participant;
    }

    /**
     * Sets the value of the participant property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeeId }
     *     
     */
    public void setParticipant(BeeId value) {
        this.participant = value;
    }

    /**
     * Gets the value of the participantStatus property.
     * 
     * @return
     *     possible object is
     *     {@link OccurrenceParticipantStatus }
     *     
     */
    public OccurrenceParticipantStatus getParticipantStatus() {
        return participantStatus;
    }

    /**
     * Sets the value of the participantStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link OccurrenceParticipantStatus }
     *     
     */
    public void setParticipantStatus(OccurrenceParticipantStatus value) {
        this.participantStatus = value;
    }

    /**
     * Gets the value of the propertiesUpdater property.
     * 
     * @return
     *     possible object is
     *     {@link CollabPropertiesUpdater }
     *     
     */
    public CollabPropertiesUpdater getPropertiesUpdater() {
        return propertiesUpdater;
    }

    /**
     * Sets the value of the propertiesUpdater property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollabPropertiesUpdater }
     *     
     */
    public void setPropertiesUpdater(CollabPropertiesUpdater value) {
        this.propertiesUpdater = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link ParticipantRole }
     *     
     */
    public ParticipantRole getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParticipantRole }
     *     
     */
    public void setRole(ParticipantRole value) {
        this.role = value;
    }

    /**
     * Gets the value of the rsvp property.
     * 
     */
    public boolean isRsvp() {
        return rsvp;
    }

    /**
     * Sets the value of the rsvp property.
     * 
     */
    public void setRsvp(boolean value) {
        this.rsvp = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link OccurrenceParticipantStatus }
     *     
     */
    public OccurrenceParticipantStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link OccurrenceParticipantStatus }
     *     
     */
    public void setStatus(OccurrenceParticipantStatus value) {
        this.status = value;
    }

}
