//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.18 at 04:52:34 PM PDT 
//


package com.oracle.beehive;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for relationshipConnectionRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="relationshipConnectionRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.oracle.com/beehive}connectionRequest">
 *       &lt;sequence>
 *         &lt;element name="searchInfo" type="{http://www.oracle.com/beehive}relationshipSearchInfo" minOccurs="0"/>
 *         &lt;element name="targets" type="{http://www.oracle.com/beehive}expertiseTarget" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "relationshipConnectionRequest", propOrder = {
    "searchInfo",
    "targets"
})
@XmlRootElement(name = "relationshipConnectionRequest")
public class RelationshipConnectionRequest
    extends ConnectionRequest
{

    protected RelationshipSearchInfo searchInfo;
    @XmlElement(nillable = true)
    protected List<ExpertiseTarget> targets;

    /**
     * Gets the value of the searchInfo property.
     * 
     * @return
     *     possible object is
     *     {@link RelationshipSearchInfo }
     *     
     */
    public RelationshipSearchInfo getSearchInfo() {
        return searchInfo;
    }

    /**
     * Sets the value of the searchInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationshipSearchInfo }
     *     
     */
    public void setSearchInfo(RelationshipSearchInfo value) {
        this.searchInfo = value;
    }

    /**
     * Gets the value of the targets property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the targets property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTargets().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExpertiseTarget }
     * 
     * 
     */
    public List<ExpertiseTarget> getTargets() {
        if (targets == null) {
            targets = new ArrayList<ExpertiseTarget>();
        }
        return this.targets;
    }

}
