//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.18 at 04:52:34 PM PDT 
//


package com.oracle.beehive;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for reminderUpdater complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="reminderUpdater">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.oracle.com/beehive}artifactUpdater">
 *       &lt;sequence>
 *         &lt;element name="trigger" type="{http://www.oracle.com/beehive}timedTrigger" minOccurs="0"/>
 *         &lt;element name="eid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="primary" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ruleUpdater" type="{http://www.oracle.com/beehive}reminderRuleUpdater" minOccurs="0"/>
 *         &lt;element name="source" type="{http://www.oracle.com/beehive}beeId" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.oracle.com/beehive}reminderStatus" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reminderUpdater", propOrder = {
    "trigger",
    "eid",
    "enabled",
    "primary",
    "ruleUpdater",
    "source",
    "status"
})
@XmlRootElement(name = "reminderUpdater")
public class ReminderUpdater
    extends ArtifactUpdater
{

    protected TimedTrigger trigger;
    protected String eid;
    protected Boolean enabled;
    protected Boolean primary;
    protected ReminderRuleUpdater ruleUpdater;
    protected BeeId source;
    protected ReminderStatus status;

    /**
     * Gets the value of the trigger property.
     * 
     * @return
     *     possible object is
     *     {@link TimedTrigger }
     *     
     */
    public TimedTrigger getTrigger() {
        return trigger;
    }

    /**
     * Sets the value of the trigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimedTrigger }
     *     
     */
    public void setTrigger(TimedTrigger value) {
        this.trigger = value;
    }

    /**
     * Gets the value of the eid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEid() {
        return eid;
    }

    /**
     * Sets the value of the eid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEid(String value) {
        this.eid = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnabled(Boolean value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the primary property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPrimary() {
        return primary;
    }

    /**
     * Sets the value of the primary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrimary(Boolean value) {
        this.primary = value;
    }

    /**
     * Gets the value of the ruleUpdater property.
     * 
     * @return
     *     possible object is
     *     {@link ReminderRuleUpdater }
     *     
     */
    public ReminderRuleUpdater getRuleUpdater() {
        return ruleUpdater;
    }

    /**
     * Sets the value of the ruleUpdater property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReminderRuleUpdater }
     *     
     */
    public void setRuleUpdater(ReminderRuleUpdater value) {
        this.ruleUpdater = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link BeeId }
     *     
     */
    public BeeId getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeeId }
     *     
     */
    public void setSource(BeeId value) {
        this.source = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link ReminderStatus }
     *     
     */
    public ReminderStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReminderStatus }
     *     
     */
    public void setStatus(ReminderStatus value) {
        this.status = value;
    }

}
