//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.18 at 04:52:34 PM PDT 
//


package com.oracle.beehive;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for wikiLinkedEntityType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="wikiLinkedEntityType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="WIKI"/>
 *     &lt;enumeration value="DOCUMENT"/>
 *     &lt;enumeration value="FOLDER"/>
 *     &lt;enumeration value="TOPIC"/>
 *     &lt;enumeration value="DISCUSSIONS_MESSAGE"/>
 *     &lt;enumeration value="ANNOUNCEMENT"/>
 *     &lt;enumeration value="TASK"/>
 *     &lt;enumeration value="TASKLIST"/>
 *     &lt;enumeration value="FORUM"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "wikiLinkedEntityType")
@XmlEnum
public enum WikiLinkedEntityType {

    WIKI,
    DOCUMENT,
    FOLDER,
    TOPIC,
    DISCUSSIONS_MESSAGE,
    ANNOUNCEMENT,
    TASK,
    TASKLIST,
    FORUM;

    public String value() {
        return name();
    }

    public static WikiLinkedEntityType fromValue(String v) {
        return valueOf(v);
    }

}
