//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.08 at 05:31:42 PM PST 
//


package com.oracle.beehive;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for artifact complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="artifact">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.oracle.com/beehive}entity">
 *       &lt;sequence>
 *         &lt;element name="bonds" type="{http://www.oracle.com/beehive}bond" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="changeStatus" type="{http://www.oracle.com/beehive}changeStatus" minOccurs="0"/>
 *         &lt;element name="properties" type="{http://www.oracle.com/beehive}collabProperties" minOccurs="0"/>
 *         &lt;element name="userCreatedOn" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="userModifiedOn" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="viewer" type="{http://www.oracle.com/beehive}actor" minOccurs="0"/>
 *         &lt;element name="viewerProperties" type="{http://www.oracle.com/beehive}collabProperties" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "artifact", propOrder = {
    "bonds",
    "changeStatus",
    "properties",
    "userCreatedOn",
    "userModifiedOn",
    "viewer",
    "viewerProperties"
})
@XmlSeeAlso({
    DefaultReminder.class,
    AuditRecord.class,
    Policy.class,
    Occurrence.class,
    AuditTrail.class,
    Workflow.class,
    Notification.class,
    Task.class,
    ExternalArtifact.class,
    WikiPage.class,
    Template.class,
    Link.class,
    Reminder.class,
    AddressBookElement.class,
    Meeting.class,
    Subscription.class,
    Message.class,
    Conference.class,
    TrashItem.class,
    Marker.class,
    Document.class,
    Folder.class
})
public abstract class Artifact
    extends Entity
{

    @XmlElement(nillable = true)
    protected List<Bond> bonds;
    protected ChangeStatus changeStatus;
    protected CollabProperties properties;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar userCreatedOn;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar userModifiedOn;
    protected Actor viewer;
    protected CollabProperties viewerProperties;

    /**
     * Gets the value of the bonds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bonds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBonds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Bond }
     * 
     * 
     */
    public List<Bond> getBonds() {
        if (bonds == null) {
            bonds = new ArrayList<Bond>();
        }
        return this.bonds;
    }

    /**
     * Gets the value of the changeStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeStatus }
     *     
     */
    public ChangeStatus getChangeStatus() {
        return changeStatus;
    }

    /**
     * Sets the value of the changeStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeStatus }
     *     
     */
    public void setChangeStatus(ChangeStatus value) {
        this.changeStatus = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link CollabProperties }
     *     
     */
    public CollabProperties getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollabProperties }
     *     
     */
    public void setProperties(CollabProperties value) {
        this.properties = value;
    }

    /**
     * Gets the value of the userCreatedOn property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUserCreatedOn() {
        return userCreatedOn;
    }

    /**
     * Sets the value of the userCreatedOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUserCreatedOn(XMLGregorianCalendar value) {
        this.userCreatedOn = value;
    }

    /**
     * Gets the value of the userModifiedOn property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUserModifiedOn() {
        return userModifiedOn;
    }

    /**
     * Sets the value of the userModifiedOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUserModifiedOn(XMLGregorianCalendar value) {
        this.userModifiedOn = value;
    }

    /**
     * Gets the value of the viewer property.
     * 
     * @return
     *     possible object is
     *     {@link Actor }
     *     
     */
    public Actor getViewer() {
        return viewer;
    }

    /**
     * Sets the value of the viewer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Actor }
     *     
     */
    public void setViewer(Actor value) {
        this.viewer = value;
    }

    /**
     * Gets the value of the viewerProperties property.
     * 
     * @return
     *     possible object is
     *     {@link CollabProperties }
     *     
     */
    public CollabProperties getViewerProperties() {
        return viewerProperties;
    }

    /**
     * Sets the value of the viewerProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollabProperties }
     *     
     */
    public void setViewerProperties(CollabProperties value) {
        this.viewerProperties = value;
    }

}
