//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.08 at 05:31:42 PM PST 
//


package com.oracle.beehive;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for basicTemplate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="basicTemplate">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.oracle.com/beehive}template">
 *       &lt;sequence>
 *         &lt;element name="attributeTemplates" type="{http://www.oracle.com/beehive}attributeTemplate" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="entitySchema" type="{http://www.oracle.com/beehive}entitySchema" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "basicTemplate", propOrder = {
    "attributeTemplates",
    "description",
    "entitySchema"
})
@XmlSeeAlso({
    RemoteRepository.class,
    SubscriptionTemplate.class,
    PolicyTemplate.class,
    DeviceProfileTemplate.class,
    CategoryTemplate.class
})
public class BasicTemplate
    extends Template
{

    @XmlElement(nillable = true)
    protected List<AttributeTemplate> attributeTemplates;
    protected String description;
    protected EntitySchema entitySchema;

    /**
     * Gets the value of the attributeTemplates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributeTemplates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributeTemplates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttributeTemplate }
     * 
     * 
     */
    public List<AttributeTemplate> getAttributeTemplates() {
        if (attributeTemplates == null) {
            attributeTemplates = new ArrayList<AttributeTemplate>();
        }
        return this.attributeTemplates;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the entitySchema property.
     * 
     * @return
     *     possible object is
     *     {@link EntitySchema }
     *     
     */
    public EntitySchema getEntitySchema() {
        return entitySchema;
    }

    /**
     * Sets the value of the entitySchema property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntitySchema }
     *     
     */
    public void setEntitySchema(EntitySchema value) {
        this.entitySchema = value;
    }

}
