//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.08 at 05:31:42 PM PST 
//


package com.oracle.beehive;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for contentEncodingType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="contentEncodingType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SEVEN_BIT"/>
 *     &lt;enumeration value="EIGHT_BIT"/>
 *     &lt;enumeration value="BASE64"/>
 *     &lt;enumeration value="QUOTED_PRINTABLE"/>
 *     &lt;enumeration value="OTHER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "contentEncodingType")
@XmlEnum
public enum ContentEncodingType {

    SEVEN_BIT("SEVEN_BIT"),
    EIGHT_BIT("EIGHT_BIT"),
    @XmlEnumValue("BASE64")
    BASE_64("BASE64"),
    QUOTED_PRINTABLE("QUOTED_PRINTABLE"),
    OTHER("OTHER");
    private final String value;

    ContentEncodingType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ContentEncodingType fromValue(String v) {
        for (ContentEncodingType c: ContentEncodingType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
