//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.08 at 05:31:42 PM PST 
//


package com.oracle.beehive;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for entityAddressScheme.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="entityAddressScheme">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AUTHID"/>
 *     &lt;enumeration value="FAX"/>
 *     &lt;enumeration value="FTP"/>
 *     &lt;enumeration value="HTTP"/>
 *     &lt;enumeration value="HTTPS"/>
 *     &lt;enumeration value="IM"/>
 *     &lt;enumeration value="ORAISDN"/>
 *     &lt;enumeration value="IMAP"/>
 *     &lt;enumeration value="LDAP"/>
 *     &lt;enumeration value="MAILTO"/>
 *     &lt;enumeration value="NEWS"/>
 *     &lt;enumeration value="NNTP"/>
 *     &lt;enumeration value="ORAALERT"/>
 *     &lt;enumeration value="ORAASSISTANTPHONE"/>
 *     &lt;enumeration value="ORACALLBACK"/>
 *     &lt;enumeration value="ORACARPHONE"/>
 *     &lt;enumeration value="ORAMOBILE"/>
 *     &lt;enumeration value="ORAPUSH"/>
 *     &lt;enumeration value="ORAPAGER"/>
 *     &lt;enumeration value="ORAPOSTAL"/>
 *     &lt;enumeration value="ORARADIO"/>
 *     &lt;enumeration value="ORASMS"/>
 *     &lt;enumeration value="ORATELEX"/>
 *     &lt;enumeration value="ORATTYTTD"/>
 *     &lt;enumeration value="ORAVMAIL"/>
 *     &lt;enumeration value="PRES"/>
 *     &lt;enumeration value="POSTAL"/>
 *     &lt;enumeration value="SIP"/>
 *     &lt;enumeration value="SMS"/>
 *     &lt;enumeration value="TEL"/>
 *     &lt;enumeration value="URN"/>
 *     &lt;enumeration value="XMPP"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "entityAddressScheme")
@XmlEnum
public enum EntityAddressScheme {

    AUTHID,
    FAX,
    FTP,
    HTTP,
    HTTPS,
    IM,
    ORAISDN,
    IMAP,
    LDAP,
    MAILTO,
    NEWS,
    NNTP,
    ORAALERT,
    ORAASSISTANTPHONE,
    ORACALLBACK,
    ORACARPHONE,
    ORAMOBILE,
    ORAPUSH,
    ORAPAGER,
    ORAPOSTAL,
    ORARADIO,
    ORASMS,
    ORATELEX,
    ORATTYTTD,
    ORAVMAIL,
    PRES,
    POSTAL,
    SIP,
    SMS,
    TEL,
    URN,
    XMPP;

    public String value() {
        return name();
    }

    public static EntityAddressScheme fromValue(String v) {
        return valueOf(v);
    }

}
