//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.08 at 05:31:42 PM PST 
//


package com.oracle.beehive;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for expertiseSearchBand complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="expertiseSearchBand">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="clauses" type="{http://www.oracle.com/beehive}expertiseSearchClause" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="maxPercent" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "expertiseSearchBand", propOrder = {
    "clauses",
    "maxPercent"
})
public class ExpertiseSearchBand {

    @XmlElement(nillable = true)
    protected List<ExpertiseSearchClause> clauses;
    protected int maxPercent;

    /**
     * Gets the value of the clauses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the clauses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClauses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExpertiseSearchClause }
     * 
     * 
     */
    public List<ExpertiseSearchClause> getClauses() {
        if (clauses == null) {
            clauses = new ArrayList<ExpertiseSearchClause>();
        }
        return this.clauses;
    }

    /**
     * Gets the value of the maxPercent property.
     * 
     */
    public int getMaxPercent() {
        return maxPercent;
    }

    /**
     * Sets the value of the maxPercent property.
     * 
     */
    public void setMaxPercent(int value) {
        this.maxPercent = value;
    }

}
