//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.08 at 05:31:42 PM PST 
//


package com.oracle.beehive;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for expertiseAggregateTopic complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="expertiseAggregateTopic">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.oracle.com/beehive}expertiseTransientTopic">
 *       &lt;sequence>
 *         &lt;element name="excludedOrganizationScopes" type="{http://www.oracle.com/beehive}expertiseOrganizationScopeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="internalState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "expertiseAggregateTopic", propOrder = {
    "excludedOrganizationScopes",
    "internalState"
})
public class ExpertiseAggregateTopic
    extends ExpertiseTransientTopic
{

    @XmlElement(nillable = true)
    protected List<ExpertiseOrganizationScopeType> excludedOrganizationScopes;
    protected String internalState;

    /**
     * Gets the value of the excludedOrganizationScopes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the excludedOrganizationScopes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExcludedOrganizationScopes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExpertiseOrganizationScopeType }
     * 
     * 
     */
    public List<ExpertiseOrganizationScopeType> getExcludedOrganizationScopes() {
        if (excludedOrganizationScopes == null) {
            excludedOrganizationScopes = new ArrayList<ExpertiseOrganizationScopeType>();
        }
        return this.excludedOrganizationScopes;
    }

    /**
     * Gets the value of the internalState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalState() {
        return internalState;
    }

    /**
     * Sets the value of the internalState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalState(String value) {
        this.internalState = value;
    }

}
