//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.08 at 05:31:42 PM PST 
//


package com.oracle.beehive;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for expertiseTopicSearchParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="expertiseTopicSearchParameters">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.oracle.com/beehive}expertiseSearchParameters">
 *       &lt;sequence>
 *         &lt;element name="maxSearchMatches" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="minProfilesForTopics" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "expertiseTopicSearchParameters", propOrder = {
    "maxSearchMatches",
    "minProfilesForTopics"
})
@XmlRootElement(name = "expertiseTopicSearchParameters")
public class ExpertiseTopicSearchParameters
    extends ExpertiseSearchParameters
{

    protected Integer maxSearchMatches;
    protected Integer minProfilesForTopics;

    /**
     * Gets the value of the maxSearchMatches property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxSearchMatches() {
        return maxSearchMatches;
    }

    /**
     * Sets the value of the maxSearchMatches property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxSearchMatches(Integer value) {
        this.maxSearchMatches = value;
    }

    /**
     * Gets the value of the minProfilesForTopics property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMinProfilesForTopics() {
        return minProfilesForTopics;
    }

    /**
     * Sets the value of the minProfilesForTopics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMinProfilesForTopics(Integer value) {
        this.minProfilesForTopics = value;
    }

}
