//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.08 at 05:31:42 PM PST 
//


package com.oracle.beehive;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for expertiseConnectionRequestCreator complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="expertiseConnectionRequestCreator">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.oracle.com/beehive}connectionRequestCreator">
 *       &lt;sequence>
 *         &lt;element name="collaborationChannel" type="{http://www.oracle.com/beehive}connectionRequestCollaborationChannel" minOccurs="0"/>
 *         &lt;element name="searchParameters" type="{http://www.oracle.com/beehive}expertiseSearchParameters" minOccurs="0"/>
 *         &lt;element name="topics" type="{http://www.oracle.com/beehive}expertiseAggregateTopic" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "expertiseConnectionRequestCreator", propOrder = {
    "collaborationChannel",
    "searchParameters",
    "topics"
})
@XmlRootElement(name = "expertiseConnectionRequestCreator")
public class ExpertiseConnectionRequestCreator
    extends ConnectionRequestCreator
{

    protected ConnectionRequestCollaborationChannel collaborationChannel;
    protected ExpertiseSearchParameters searchParameters;
    @XmlElement(nillable = true)
    protected List<ExpertiseAggregateTopic> topics;

    /**
     * Gets the value of the collaborationChannel property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectionRequestCollaborationChannel }
     *     
     */
    public ConnectionRequestCollaborationChannel getCollaborationChannel() {
        return collaborationChannel;
    }

    /**
     * Sets the value of the collaborationChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectionRequestCollaborationChannel }
     *     
     */
    public void setCollaborationChannel(ConnectionRequestCollaborationChannel value) {
        this.collaborationChannel = value;
    }

    /**
     * Gets the value of the searchParameters property.
     * 
     * @return
     *     possible object is
     *     {@link ExpertiseSearchParameters }
     *     
     */
    public ExpertiseSearchParameters getSearchParameters() {
        return searchParameters;
    }

    /**
     * Sets the value of the searchParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpertiseSearchParameters }
     *     
     */
    public void setSearchParameters(ExpertiseSearchParameters value) {
        this.searchParameters = value;
    }

    /**
     * Gets the value of the topics property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the topics property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTopics().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExpertiseAggregateTopic }
     * 
     * 
     */
    public List<ExpertiseAggregateTopic> getTopics() {
        if (topics == null) {
            topics = new ArrayList<ExpertiseAggregateTopic>();
        }
        return this.topics;
    }

}
