//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.08 at 05:31:42 PM PST 
//


package com.oracle.beehive;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for internalResource complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="internalResource">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.oracle.com/beehive}actor">
 *       &lt;sequence>
 *         &lt;element name="bookingBehavior" type="{http://www.oracle.com/beehive}bookingBehavior" minOccurs="0"/>
 *         &lt;element name="bookingInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="capacity" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="classification" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="classificationChanged" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="identifier" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="resourceType" type="{http://www.oracle.com/beehive}resourceType" minOccurs="0"/>
 *         &lt;element name="resourceWorkspace" type="{http://www.oracle.com/beehive}workspace" minOccurs="0"/>
 *         &lt;element name="staticLocation" type="{http://www.oracle.com/beehive}location" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "internalResource", propOrder = {
    "bookingBehavior",
    "bookingInfo",
    "capacity",
    "classification",
    "classificationChanged",
    "description",
    "identifier",
    "resourceType",
    "resourceWorkspace",
    "staticLocation"
})
@XmlSeeAlso({
    BookableResource.class
})
public abstract class InternalResource
    extends Actor
{

    protected BookingBehavior bookingBehavior;
    protected String bookingInfo;
    protected Integer capacity;
    protected String classification;
    protected String classificationChanged;
    protected String description;
    protected String identifier;
    protected ResourceType resourceType;
    protected Workspace resourceWorkspace;
    protected Location staticLocation;

    /**
     * Gets the value of the bookingBehavior property.
     * 
     * @return
     *     possible object is
     *     {@link BookingBehavior }
     *     
     */
    public BookingBehavior getBookingBehavior() {
        return bookingBehavior;
    }

    /**
     * Sets the value of the bookingBehavior property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookingBehavior }
     *     
     */
    public void setBookingBehavior(BookingBehavior value) {
        this.bookingBehavior = value;
    }

    /**
     * Gets the value of the bookingInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookingInfo() {
        return bookingInfo;
    }

    /**
     * Sets the value of the bookingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingInfo(String value) {
        this.bookingInfo = value;
    }

    /**
     * Gets the value of the capacity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCapacity() {
        return capacity;
    }

    /**
     * Sets the value of the capacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCapacity(Integer value) {
        this.capacity = value;
    }

    /**
     * Gets the value of the classification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassification() {
        return classification;
    }

    /**
     * Sets the value of the classification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassification(String value) {
        this.classification = value;
    }

    /**
     * Gets the value of the classificationChanged property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassificationChanged() {
        return classificationChanged;
    }

    /**
     * Sets the value of the classificationChanged property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassificationChanged(String value) {
        this.classificationChanged = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the resourceType property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceType }
     *     
     */
    public ResourceType getResourceType() {
        return resourceType;
    }

    /**
     * Sets the value of the resourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceType }
     *     
     */
    public void setResourceType(ResourceType value) {
        this.resourceType = value;
    }

    /**
     * Gets the value of the resourceWorkspace property.
     * 
     * @return
     *     possible object is
     *     {@link Workspace }
     *     
     */
    public Workspace getResourceWorkspace() {
        return resourceWorkspace;
    }

    /**
     * Sets the value of the resourceWorkspace property.
     * 
     * @param value
     *     allowed object is
     *     {@link Workspace }
     *     
     */
    public void setResourceWorkspace(Workspace value) {
        this.resourceWorkspace = value;
    }

    /**
     * Gets the value of the staticLocation property.
     * 
     * @return
     *     possible object is
     *     {@link Location }
     *     
     */
    public Location getStaticLocation() {
        return staticLocation;
    }

    /**
     * Sets the value of the staticLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Location }
     *     
     */
    public void setStaticLocation(Location value) {
        this.staticLocation = value;
    }

}
