//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.08 at 05:31:42 PM PST 
//


package com.oracle.beehive;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for labelAppTypePredicate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="labelAppTypePredicate">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.oracle.com/beehive}predicate">
 *       &lt;sequence>
 *         &lt;element name="labelApplicationType" type="{http://www.oracle.com/beehive}labelApplicationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "labelAppTypePredicate", propOrder = {
    "labelApplicationType"
})
public class LabelAppTypePredicate
    extends Predicate
{

    protected LabelApplicationType labelApplicationType;

    /**
     * Gets the value of the labelApplicationType property.
     * 
     * @return
     *     possible object is
     *     {@link LabelApplicationType }
     *     
     */
    public LabelApplicationType getLabelApplicationType() {
        return labelApplicationType;
    }

    /**
     * Sets the value of the labelApplicationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link LabelApplicationType }
     *     
     */
    public void setLabelApplicationType(LabelApplicationType value) {
        this.labelApplicationType = value;
    }

}
