//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.08 at 05:31:42 PM PST 
//


package com.oracle.beehive;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pagingOptions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pagingOptions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="count" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="fetchMode" type="{http://www.oracle.com/beehive}fetchMode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pagingOptions", propOrder = {
    "count",
    "fetchMode"
})
@XmlSeeAlso({
    NumericPagingOptions.class,
    TimePagingOptions.class,
    TimestampedPagingOptions.class
})
public abstract class PagingOptions {

    protected int count;
    protected FetchMode fetchMode;

    /**
     * Gets the value of the count property.
     * 
     */
    public int getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     */
    public void setCount(int value) {
        this.count = value;
    }

    /**
     * Gets the value of the fetchMode property.
     * 
     * @return
     *     possible object is
     *     {@link FetchMode }
     *     
     */
    public FetchMode getFetchMode() {
        return fetchMode;
    }

    /**
     * Sets the value of the fetchMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link FetchMode }
     *     
     */
    public void setFetchMode(FetchMode value) {
        this.fetchMode = value;
    }

}
