//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.08 at 05:31:42 PM PST 
//


package com.oracle.beehive;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for personalWorkspace complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="personalWorkspace">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.oracle.com/beehive}workspace">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.oracle.com/beehive}reminderList" minOccurs="0"/>
 *         &lt;element ref="{http://www.oracle.com/beehive}subscriptionList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "personalWorkspace", propOrder = {
    "reminderList",
    "subscriptionList"
})
@XmlRootElement(name = "personalWorkspace")
public class PersonalWorkspace
    extends Workspace
{

    protected ReminderList reminderList;
    protected SubscriptionList subscriptionList;

    /**
     * Gets the value of the reminderList property.
     * 
     * @return
     *     possible object is
     *     {@link ReminderList }
     *     
     */
    public ReminderList getReminderList() {
        return reminderList;
    }

    /**
     * Sets the value of the reminderList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReminderList }
     *     
     */
    public void setReminderList(ReminderList value) {
        this.reminderList = value;
    }

    /**
     * Gets the value of the subscriptionList property.
     * 
     * @return
     *     possible object is
     *     {@link SubscriptionList }
     *     
     */
    public SubscriptionList getSubscriptionList() {
        return subscriptionList;
    }

    /**
     * Sets the value of the subscriptionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscriptionList }
     *     
     */
    public void setSubscriptionList(SubscriptionList value) {
        this.subscriptionList = value;
    }

}
