//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.08 at 05:31:42 PM PST 
//


package com.oracle.beehive;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for timeZoneOnsetOrdinalWeekDayOfMonth complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="timeZoneOnsetOrdinalWeekDayOfMonth">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.oracle.com/beehive}timeZoneOnsetMovableDay">
 *       &lt;sequence>
 *         &lt;element name="position" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="weekDay" type="{http://www.oracle.com/beehive}weekDay"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "timeZoneOnsetOrdinalWeekDayOfMonth", propOrder = {
    "position",
    "weekDay"
})
public class TimeZoneOnsetOrdinalWeekDayOfMonth
    extends TimeZoneOnsetMovableDay
{

    protected int position;
    @XmlElement(required = true)
    protected WeekDay weekDay;

    /**
     * Gets the value of the position property.
     * 
     */
    public int getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     */
    public void setPosition(int value) {
        this.position = value;
    }

    /**
     * Gets the value of the weekDay property.
     * 
     * @return
     *     possible object is
     *     {@link WeekDay }
     *     
     */
    public WeekDay getWeekDay() {
        return weekDay;
    }

    /**
     * Sets the value of the weekDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeekDay }
     *     
     */
    public void setWeekDay(WeekDay value) {
        this.weekDay = value;
    }

}
