//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.08 at 05:31:42 PM PST 
//


package com.oracle.beehive;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for workflowCreator complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="workflowCreator">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.oracle.com/beehive}entityCreator">
 *       &lt;sequence>
 *         &lt;element name="updater" type="{http://www.oracle.com/beehive}workflowUpdater" minOccurs="0"/>
 *         &lt;element name="wfhdl" type="{http://www.oracle.com/beehive}beeId" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "workflowCreator", propOrder = {
    "updater",
    "wfhdl"
})
public class WorkflowCreator
    extends EntityCreator
{

    protected WorkflowUpdater updater;
    protected BeeId wfhdl;

    /**
     * Gets the value of the updater property.
     * 
     * @return
     *     possible object is
     *     {@link WorkflowUpdater }
     *     
     */
    public WorkflowUpdater getUpdater() {
        return updater;
    }

    /**
     * Sets the value of the updater property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkflowUpdater }
     *     
     */
    public void setUpdater(WorkflowUpdater value) {
        this.updater = value;
    }

    /**
     * Gets the value of the wfhdl property.
     * 
     * @return
     *     possible object is
     *     {@link BeeId }
     *     
     */
    public BeeId getWfhdl() {
        return wfhdl;
    }

    /**
     * Sets the value of the wfhdl property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeeId }
     *     
     */
    public void setWfhdl(BeeId value) {
        this.wfhdl = value;
    }

}
