//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.27 at 04:52:46 PM PST 
//


package com.oracle.beehive;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for calendarUpdater complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="calendarUpdater">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.oracle.com/beehive}folderUpdater">
 *       &lt;sequence>
 *         &lt;element name="availableHours" type="{http://www.oracle.com/beehive}businessHours" minOccurs="0"/>
 *         &lt;element name="bookingBehavior" type="{http://www.oracle.com/beehive}bookingBehavior" minOccurs="0"/>
 *         &lt;element name="calDavResourceName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="canParticipantsPresentScheduledOnlineConference" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="defaultICalPriority" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="defaultJournal" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="defaultPriority" type="{http://www.oracle.com/beehive}priority" minOccurs="0"/>
 *         &lt;element name="defaultSensitivity" type="{http://www.oracle.com/beehive}beeId" minOccurs="0"/>
 *         &lt;element name="deriveAvailableHoursFromOwnerWorkingHours" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="directEnrollmentsUpdater" type="{http://www.oracle.com/beehive}calendarEnrollmentListUpdater" minOccurs="0"/>
 *         &lt;element name="directUnenrollmentsUpdater" type="{http://www.oracle.com/beehive}calendarEnrollmentListUpdater" minOccurs="0"/>
 *         &lt;element name="enablePresenceIntegration" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="enrollWorkspaceMembers" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="enrolled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="enrollmentType" type="{http://www.oracle.com/beehive}enrollmentType" minOccurs="0"/>
 *         &lt;element name="includeInFreeBusy" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="inheritTimeZoneFromOwner" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="selfEnrollmentOpenToAll" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="timeZone" type="{http://www.oracle.com/beehive}beeId" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "calendarUpdater", propOrder = {
    "availableHours",
    "bookingBehavior",
    "calDavResourceName",
    "canParticipantsPresentScheduledOnlineConference",
    "defaultICalPriority",
    "defaultJournal",
    "defaultPriority",
    "defaultSensitivity",
    "deriveAvailableHoursFromOwnerWorkingHours",
    "directEnrollmentsUpdater",
    "directUnenrollmentsUpdater",
    "enablePresenceIntegration",
    "enrollWorkspaceMembers",
    "enrolled",
    "enrollmentType",
    "includeInFreeBusy",
    "inheritTimeZoneFromOwner",
    "selfEnrollmentOpenToAll",
    "timeZone"
})
public class CalendarUpdater
    extends FolderUpdater
{

    protected BusinessHours availableHours;
    protected BookingBehavior bookingBehavior;
    protected String calDavResourceName;
    protected boolean canParticipantsPresentScheduledOnlineConference;
    protected int defaultICalPriority;
    protected boolean defaultJournal;
    protected Priority defaultPriority;
    protected BeeId defaultSensitivity;
    protected boolean deriveAvailableHoursFromOwnerWorkingHours;
    protected CalendarEnrollmentListUpdater directEnrollmentsUpdater;
    protected CalendarEnrollmentListUpdater directUnenrollmentsUpdater;
    protected boolean enablePresenceIntegration;
    protected boolean enrollWorkspaceMembers;
    protected boolean enrolled;
    protected EnrollmentType enrollmentType;
    protected boolean includeInFreeBusy;
    protected boolean inheritTimeZoneFromOwner;
    protected boolean selfEnrollmentOpenToAll;
    protected BeeId timeZone;

    /**
     * Gets the value of the availableHours property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessHours }
     *     
     */
    public BusinessHours getAvailableHours() {
        return availableHours;
    }

    /**
     * Sets the value of the availableHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessHours }
     *     
     */
    public void setAvailableHours(BusinessHours value) {
        this.availableHours = value;
    }

    /**
     * Gets the value of the bookingBehavior property.
     * 
     * @return
     *     possible object is
     *     {@link BookingBehavior }
     *     
     */
    public BookingBehavior getBookingBehavior() {
        return bookingBehavior;
    }

    /**
     * Sets the value of the bookingBehavior property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookingBehavior }
     *     
     */
    public void setBookingBehavior(BookingBehavior value) {
        this.bookingBehavior = value;
    }

    /**
     * Gets the value of the calDavResourceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalDavResourceName() {
        return calDavResourceName;
    }

    /**
     * Sets the value of the calDavResourceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalDavResourceName(String value) {
        this.calDavResourceName = value;
    }

    /**
     * Gets the value of the canParticipantsPresentScheduledOnlineConference property.
     * 
     */
    public boolean isCanParticipantsPresentScheduledOnlineConference() {
        return canParticipantsPresentScheduledOnlineConference;
    }

    /**
     * Sets the value of the canParticipantsPresentScheduledOnlineConference property.
     * 
     */
    public void setCanParticipantsPresentScheduledOnlineConference(boolean value) {
        this.canParticipantsPresentScheduledOnlineConference = value;
    }

    /**
     * Gets the value of the defaultICalPriority property.
     * 
     */
    public int getDefaultICalPriority() {
        return defaultICalPriority;
    }

    /**
     * Sets the value of the defaultICalPriority property.
     * 
     */
    public void setDefaultICalPriority(int value) {
        this.defaultICalPriority = value;
    }

    /**
     * Gets the value of the defaultJournal property.
     * 
     */
    public boolean isDefaultJournal() {
        return defaultJournal;
    }

    /**
     * Sets the value of the defaultJournal property.
     * 
     */
    public void setDefaultJournal(boolean value) {
        this.defaultJournal = value;
    }

    /**
     * Gets the value of the defaultPriority property.
     * 
     * @return
     *     possible object is
     *     {@link Priority }
     *     
     */
    public Priority getDefaultPriority() {
        return defaultPriority;
    }

    /**
     * Sets the value of the defaultPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Priority }
     *     
     */
    public void setDefaultPriority(Priority value) {
        this.defaultPriority = value;
    }

    /**
     * Gets the value of the defaultSensitivity property.
     * 
     * @return
     *     possible object is
     *     {@link BeeId }
     *     
     */
    public BeeId getDefaultSensitivity() {
        return defaultSensitivity;
    }

    /**
     * Sets the value of the defaultSensitivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeeId }
     *     
     */
    public void setDefaultSensitivity(BeeId value) {
        this.defaultSensitivity = value;
    }

    /**
     * Gets the value of the deriveAvailableHoursFromOwnerWorkingHours property.
     * 
     */
    public boolean isDeriveAvailableHoursFromOwnerWorkingHours() {
        return deriveAvailableHoursFromOwnerWorkingHours;
    }

    /**
     * Sets the value of the deriveAvailableHoursFromOwnerWorkingHours property.
     * 
     */
    public void setDeriveAvailableHoursFromOwnerWorkingHours(boolean value) {
        this.deriveAvailableHoursFromOwnerWorkingHours = value;
    }

    /**
     * Gets the value of the directEnrollmentsUpdater property.
     * 
     * @return
     *     possible object is
     *     {@link CalendarEnrollmentListUpdater }
     *     
     */
    public CalendarEnrollmentListUpdater getDirectEnrollmentsUpdater() {
        return directEnrollmentsUpdater;
    }

    /**
     * Sets the value of the directEnrollmentsUpdater property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalendarEnrollmentListUpdater }
     *     
     */
    public void setDirectEnrollmentsUpdater(CalendarEnrollmentListUpdater value) {
        this.directEnrollmentsUpdater = value;
    }

    /**
     * Gets the value of the directUnenrollmentsUpdater property.
     * 
     * @return
     *     possible object is
     *     {@link CalendarEnrollmentListUpdater }
     *     
     */
    public CalendarEnrollmentListUpdater getDirectUnenrollmentsUpdater() {
        return directUnenrollmentsUpdater;
    }

    /**
     * Sets the value of the directUnenrollmentsUpdater property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalendarEnrollmentListUpdater }
     *     
     */
    public void setDirectUnenrollmentsUpdater(CalendarEnrollmentListUpdater value) {
        this.directUnenrollmentsUpdater = value;
    }

    /**
     * Gets the value of the enablePresenceIntegration property.
     * 
     */
    public boolean isEnablePresenceIntegration() {
        return enablePresenceIntegration;
    }

    /**
     * Sets the value of the enablePresenceIntegration property.
     * 
     */
    public void setEnablePresenceIntegration(boolean value) {
        this.enablePresenceIntegration = value;
    }

    /**
     * Gets the value of the enrollWorkspaceMembers property.
     * 
     */
    public boolean isEnrollWorkspaceMembers() {
        return enrollWorkspaceMembers;
    }

    /**
     * Sets the value of the enrollWorkspaceMembers property.
     * 
     */
    public void setEnrollWorkspaceMembers(boolean value) {
        this.enrollWorkspaceMembers = value;
    }

    /**
     * Gets the value of the enrolled property.
     * 
     */
    public boolean isEnrolled() {
        return enrolled;
    }

    /**
     * Sets the value of the enrolled property.
     * 
     */
    public void setEnrolled(boolean value) {
        this.enrolled = value;
    }

    /**
     * Gets the value of the enrollmentType property.
     * 
     * @return
     *     possible object is
     *     {@link EnrollmentType }
     *     
     */
    public EnrollmentType getEnrollmentType() {
        return enrollmentType;
    }

    /**
     * Sets the value of the enrollmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnrollmentType }
     *     
     */
    public void setEnrollmentType(EnrollmentType value) {
        this.enrollmentType = value;
    }

    /**
     * Gets the value of the includeInFreeBusy property.
     * 
     */
    public boolean isIncludeInFreeBusy() {
        return includeInFreeBusy;
    }

    /**
     * Sets the value of the includeInFreeBusy property.
     * 
     */
    public void setIncludeInFreeBusy(boolean value) {
        this.includeInFreeBusy = value;
    }

    /**
     * Gets the value of the inheritTimeZoneFromOwner property.
     * 
     */
    public boolean isInheritTimeZoneFromOwner() {
        return inheritTimeZoneFromOwner;
    }

    /**
     * Sets the value of the inheritTimeZoneFromOwner property.
     * 
     */
    public void setInheritTimeZoneFromOwner(boolean value) {
        this.inheritTimeZoneFromOwner = value;
    }

    /**
     * Gets the value of the selfEnrollmentOpenToAll property.
     * 
     */
    public boolean isSelfEnrollmentOpenToAll() {
        return selfEnrollmentOpenToAll;
    }

    /**
     * Sets the value of the selfEnrollmentOpenToAll property.
     * 
     */
    public void setSelfEnrollmentOpenToAll(boolean value) {
        this.selfEnrollmentOpenToAll = value;
    }

    /**
     * Gets the value of the timeZone property.
     * 
     * @return
     *     possible object is
     *     {@link BeeId }
     *     
     */
    public BeeId getTimeZone() {
        return timeZone;
    }

    /**
     * Sets the value of the timeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeeId }
     *     
     */
    public void setTimeZone(BeeId value) {
        this.timeZone = value;
    }

}
