//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.27 at 04:52:46 PM PST 
//


package com.oracle.beehive;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for feedConfigurationCreator complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="feedConfigurationCreator">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.oracle.com/beehive}entityCreator">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fdCfgUpdtr" type="{http://www.oracle.com/beehive}feedConfigurationUpdater" minOccurs="0"/>
 *         &lt;element name="fdTyp" type="{http://www.oracle.com/beehive}feedType" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="scpHndl" type="{http://www.oracle.com/beehive}beeId" minOccurs="0"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "feedConfigurationCreator", propOrder = {
    "description",
    "fdCfgUpdtr",
    "fdTyp",
    "name",
    "scpHndl",
    "title"
})
public class FeedConfigurationCreator
    extends EntityCreator
{

    protected String description;
    protected FeedConfigurationUpdater fdCfgUpdtr;
    protected FeedType fdTyp;
    protected String name;
    protected BeeId scpHndl;
    protected String title;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the fdCfgUpdtr property.
     * 
     * @return
     *     possible object is
     *     {@link FeedConfigurationUpdater }
     *     
     */
    public FeedConfigurationUpdater getFdCfgUpdtr() {
        return fdCfgUpdtr;
    }

    /**
     * Sets the value of the fdCfgUpdtr property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeedConfigurationUpdater }
     *     
     */
    public void setFdCfgUpdtr(FeedConfigurationUpdater value) {
        this.fdCfgUpdtr = value;
    }

    /**
     * Gets the value of the fdTyp property.
     * 
     * @return
     *     possible object is
     *     {@link FeedType }
     *     
     */
    public FeedType getFdTyp() {
        return fdTyp;
    }

    /**
     * Sets the value of the fdTyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeedType }
     *     
     */
    public void setFdTyp(FeedType value) {
        this.fdTyp = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the scpHndl property.
     * 
     * @return
     *     possible object is
     *     {@link BeeId }
     *     
     */
    public BeeId getScpHndl() {
        return scpHndl;
    }

    /**
     * Sets the value of the scpHndl property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeeId }
     *     
     */
    public void setScpHndl(BeeId value) {
        this.scpHndl = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

}
