//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.27 at 04:52:46 PM PST 
//


package com.oracle.beehive;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for identifiableUpdater complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="identifiableUpdater">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "identifiableUpdater")
@XmlSeeAlso({
    AnswerStatusUpdater.class,
    DiscussionsMessageDeletePermissionsUpdater.class,
    DiscussionsMessageUpdatePermissionsUpdater.class,
    MultiContentTrimmer.class,
    ReminderRuleUpdater.class,
    PreferencePropertiesUpdater.class,
    ConferenceSettingsUpdater.class,
    ExternalContactListUpdater.class,
    CategoryApplicationListUpdater.class,
    AttributeApplicationListUpdater.class,
    AttributeTemplateListUpdater.class,
    RuleActionDefinitionUpdater.class,
    FeedConfigurationUpdater.class,
    AttributeTemplateUpdater.class,
    VersionControlConfigurationUpdater.class,
    CategoryConfigurationUpdater.class,
    OccurrenceListUpdater.class,
    NotificationContentInfoListUpdater.class,
    RuleTemplateUpdater.class,
    OnlineInstantMessageSetsUpdater.class,
    CalendarEnrollmentListUpdater.class,
    ConferenceRoleUpdater.class,
    RuleDefinitionListUpdater.class,
    RuleUpdater.class,
    RuleListUpdater.class,
    OccurrenceParticipantListUpdater.class,
    OccurrenceCompositeParticipantListUpdater.class,
    InstalledClientApplicationUpdater.class,
    TodoCompositeParticipantListUpdater.class,
    RuleTemplateListUpdater.class,
    AttachmentListUpdater.class,
    ExternalContactUpdater.class,
    XmppChatRoomMembersUpdater.class,
    TodoParticipantListUpdater.class,
    AttributeDefinitionUpdater.class,
    CategoryTemplateListUpdater.class,
    RuleDefinitionUpdater.class,
    InvitationListUpdater.class,
    BaseParticipantUpdater.class,
    InstalledClientApplicationListUpdater.class,
    AttributeDefinitionListUpdater.class,
    DeviceCommandListUpdater.class,
    ContentUpdater.class,
    AccessControlFieldsUpdater.class,
    EntityUpdater.class
})
public class IdentifiableUpdater {


}
