//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.27 at 04:52:46 PM PST 
//


package com.oracle.beehive;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for simpleContentUpdater complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="simpleContentUpdater">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.oracle.com/beehive}simpleContentBaseUpdater">
 *       &lt;sequence>
 *         &lt;element name="contentBytes" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="eid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.oracle.com/beehive}rawString" minOccurs="0"/>
 *         &lt;element name="piecewiseUpdate" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="size" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "simpleContentUpdater", propOrder = {
    "contentBytes",
    "eid",
    "name",
    "piecewiseUpdate",
    "size"
})
public class SimpleContentUpdater
    extends SimpleContentBaseUpdater
{

    protected byte[] contentBytes;
    protected String eid;
    protected RawString name;
    protected Boolean piecewiseUpdate;
    protected Long size;

    /**
     * Gets the value of the contentBytes property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getContentBytes() {
        return contentBytes;
    }

    /**
     * Sets the value of the contentBytes property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setContentBytes(byte[] value) {
        this.contentBytes = ((byte[]) value);
    }

    /**
     * Gets the value of the eid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEid() {
        return eid;
    }

    /**
     * Sets the value of the eid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEid(String value) {
        this.eid = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link RawString }
     *     
     */
    public RawString getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link RawString }
     *     
     */
    public void setName(RawString value) {
        this.name = value;
    }

    /**
     * Gets the value of the piecewiseUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPiecewiseUpdate() {
        return piecewiseUpdate;
    }

    /**
     * Sets the value of the piecewiseUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPiecewiseUpdate(Boolean value) {
        this.piecewiseUpdate = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSize(Long value) {
        this.size = value;
    }

}
