//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.27 at 04:52:46 PM PST 
//


package com.oracle.beehive;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for subscription complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="subscription">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.oracle.com/beehive}artifact">
 *       &lt;sequence>
 *         &lt;element name="attachedTo" type="{http://www.oracle.com/beehive}beeId" minOccurs="0"/>
 *         &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="materializedSubscription" type="{http://www.oracle.com/beehive}materializedSubscription" minOccurs="0"/>
 *         &lt;element name="subscriber" type="{http://www.oracle.com/beehive}organizationUser" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "subscription", propOrder = {
    "attachedTo",
    "enabled",
    "materializedSubscription",
    "subscriber"
})
@XmlRootElement(name = "subscription")
public class Subscription
    extends Artifact
{

    protected BeeId attachedTo;
    protected boolean enabled;
    protected MaterializedSubscription materializedSubscription;
    protected OrganizationUser subscriber;

    /**
     * Gets the value of the attachedTo property.
     * 
     * @return
     *     possible object is
     *     {@link BeeId }
     *     
     */
    public BeeId getAttachedTo() {
        return attachedTo;
    }

    /**
     * Sets the value of the attachedTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeeId }
     *     
     */
    public void setAttachedTo(BeeId value) {
        this.attachedTo = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     */
    public void setEnabled(boolean value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the materializedSubscription property.
     * 
     * @return
     *     possible object is
     *     {@link MaterializedSubscription }
     *     
     */
    public MaterializedSubscription getMaterializedSubscription() {
        return materializedSubscription;
    }

    /**
     * Sets the value of the materializedSubscription property.
     * 
     * @param value
     *     allowed object is
     *     {@link MaterializedSubscription }
     *     
     */
    public void setMaterializedSubscription(MaterializedSubscription value) {
        this.materializedSubscription = value;
    }

    /**
     * Gets the value of the subscriber property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationUser }
     *     
     */
    public OrganizationUser getSubscriber() {
        return subscriber;
    }

    /**
     * Sets the value of the subscriber property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationUser }
     *     
     */
    public void setSubscriber(OrganizationUser value) {
        this.subscriber = value;
    }

}
