//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.27 at 04:52:46 PM PST 
//


package com.oracle.beehive;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for wikiPageRenderMode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wikiPageRenderMode">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="wikiLinkContext" type="{http://www.oracle.com/beehive}wikiLinkContext" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wikiPageRenderMode", propOrder = {
    "wikiLinkContext"
})
public class WikiPageRenderMode {

    protected WikiLinkContext wikiLinkContext;

    /**
     * Gets the value of the wikiLinkContext property.
     * 
     * @return
     *     possible object is
     *     {@link WikiLinkContext }
     *     
     */
    public WikiLinkContext getWikiLinkContext() {
        return wikiLinkContext;
    }

    /**
     * Sets the value of the wikiLinkContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link WikiLinkContext }
     *     
     */
    public void setWikiLinkContext(WikiLinkContext value) {
        this.wikiLinkContext = value;
    }

}
