//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.27 at 04:52:46 PM PST 
//


package com.oracle.beehive;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for workspaceUpdater complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="workspaceUpdater">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.oracle.com/beehive}scopeUpdater">
 *       &lt;sequence>
 *         &lt;element name="defaultDocumentsFolder" type="{http://www.oracle.com/beehive}beeId" minOccurs="0"/>
 *         &lt;element name="defaultSensitivity" type="{http://www.oracle.com/beehive}beeId" minOccurs="0"/>
 *         &lt;element name="defaultWikiFolder" type="{http://www.oracle.com/beehive}beeId" minOccurs="0"/>
 *         &lt;element name="defaultWikiPage" type="{http://www.oracle.com/beehive}beeId" minOccurs="0"/>
 *         &lt;element name="logoURI" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="primaryContact" type="{http://www.oracle.com/beehive}beeId" minOccurs="0"/>
 *         &lt;element name="publicSummaryURI" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="quotaConfiguration" type="{http://www.oracle.com/beehive}workspaceQuotaConfiguration" minOccurs="0"/>
 *         &lt;element name="summaryURI" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="workspaceOwner" type="{http://www.oracle.com/beehive}beeId" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "workspaceUpdater", propOrder = {
    "defaultDocumentsFolder",
    "defaultSensitivity",
    "defaultWikiFolder",
    "defaultWikiPage",
    "logoURI",
    "primaryContact",
    "publicSummaryURI",
    "quotaConfiguration",
    "summaryURI",
    "workspaceOwner"
})
@XmlSeeAlso({
    PersonalWorkspaceUpdater.class,
    TeamWorkspaceUpdater.class
})
public abstract class WorkspaceUpdater
    extends ScopeUpdater
{

    protected BeeId defaultDocumentsFolder;
    protected BeeId defaultSensitivity;
    protected BeeId defaultWikiFolder;
    protected BeeId defaultWikiPage;
    protected String logoURI;
    protected BeeId primaryContact;
    protected String publicSummaryURI;
    protected WorkspaceQuotaConfiguration quotaConfiguration;
    protected String summaryURI;
    protected BeeId workspaceOwner;

    /**
     * Gets the value of the defaultDocumentsFolder property.
     * 
     * @return
     *     possible object is
     *     {@link BeeId }
     *     
     */
    public BeeId getDefaultDocumentsFolder() {
        return defaultDocumentsFolder;
    }

    /**
     * Sets the value of the defaultDocumentsFolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeeId }
     *     
     */
    public void setDefaultDocumentsFolder(BeeId value) {
        this.defaultDocumentsFolder = value;
    }

    /**
     * Gets the value of the defaultSensitivity property.
     * 
     * @return
     *     possible object is
     *     {@link BeeId }
     *     
     */
    public BeeId getDefaultSensitivity() {
        return defaultSensitivity;
    }

    /**
     * Sets the value of the defaultSensitivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeeId }
     *     
     */
    public void setDefaultSensitivity(BeeId value) {
        this.defaultSensitivity = value;
    }

    /**
     * Gets the value of the defaultWikiFolder property.
     * 
     * @return
     *     possible object is
     *     {@link BeeId }
     *     
     */
    public BeeId getDefaultWikiFolder() {
        return defaultWikiFolder;
    }

    /**
     * Sets the value of the defaultWikiFolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeeId }
     *     
     */
    public void setDefaultWikiFolder(BeeId value) {
        this.defaultWikiFolder = value;
    }

    /**
     * Gets the value of the defaultWikiPage property.
     * 
     * @return
     *     possible object is
     *     {@link BeeId }
     *     
     */
    public BeeId getDefaultWikiPage() {
        return defaultWikiPage;
    }

    /**
     * Sets the value of the defaultWikiPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeeId }
     *     
     */
    public void setDefaultWikiPage(BeeId value) {
        this.defaultWikiPage = value;
    }

    /**
     * Gets the value of the logoURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogoURI() {
        return logoURI;
    }

    /**
     * Sets the value of the logoURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogoURI(String value) {
        this.logoURI = value;
    }

    /**
     * Gets the value of the primaryContact property.
     * 
     * @return
     *     possible object is
     *     {@link BeeId }
     *     
     */
    public BeeId getPrimaryContact() {
        return primaryContact;
    }

    /**
     * Sets the value of the primaryContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeeId }
     *     
     */
    public void setPrimaryContact(BeeId value) {
        this.primaryContact = value;
    }

    /**
     * Gets the value of the publicSummaryURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublicSummaryURI() {
        return publicSummaryURI;
    }

    /**
     * Sets the value of the publicSummaryURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublicSummaryURI(String value) {
        this.publicSummaryURI = value;
    }

    /**
     * Gets the value of the quotaConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link WorkspaceQuotaConfiguration }
     *     
     */
    public WorkspaceQuotaConfiguration getQuotaConfiguration() {
        return quotaConfiguration;
    }

    /**
     * Sets the value of the quotaConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkspaceQuotaConfiguration }
     *     
     */
    public void setQuotaConfiguration(WorkspaceQuotaConfiguration value) {
        this.quotaConfiguration = value;
    }

    /**
     * Gets the value of the summaryURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummaryURI() {
        return summaryURI;
    }

    /**
     * Sets the value of the summaryURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummaryURI(String value) {
        this.summaryURI = value;
    }

    /**
     * Gets the value of the workspaceOwner property.
     * 
     * @return
     *     possible object is
     *     {@link BeeId }
     *     
     */
    public BeeId getWorkspaceOwner() {
        return workspaceOwner;
    }

    /**
     * Sets the value of the workspaceOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeeId }
     *     
     */
    public void setWorkspaceOwner(BeeId value) {
        this.workspaceOwner = value;
    }

}
