//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.27 at 04:52:46 PM PST 
//


package com.oracle.beehive;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for xmppChatRoomCreator complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="xmppChatRoomCreator">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.oracle.com/beehive}entityCreator">
 *       &lt;sequence>
 *         &lt;element name="roomUpdater" type="{http://www.oracle.com/beehive}xmppChatRoomUpdater" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xmppChatRoomCreator", propOrder = {
    "roomUpdater"
})
public class XmppChatRoomCreator
    extends EntityCreator
{

    protected XmppChatRoomUpdater roomUpdater;

    /**
     * Gets the value of the roomUpdater property.
     * 
     * @return
     *     possible object is
     *     {@link XmppChatRoomUpdater }
     *     
     */
    public XmppChatRoomUpdater getRoomUpdater() {
        return roomUpdater;
    }

    /**
     * Sets the value of the roomUpdater property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmppChatRoomUpdater }
     *     
     */
    public void setRoomUpdater(XmppChatRoomUpdater value) {
        this.roomUpdater = value;
    }

}
